---
title: "Convert Seurat to Anndata"
author: "Carla Cohen"
date: "`r Sys.Date()`"
output: html_document
---
Aim to convert seurat objects to anndata format

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(zellkonverter)
library(tidyverse)
library(scRNAseq)

# make a new output folder for each run, with the date & time in the directory name
date <- Sys.Date() %>% str_replace_all("-", "")
time <- format(Sys.time(), "%X") %>% 
str_replace_all(":", "-") %>%
    str_sub(1,5)
directory <- paste0(date,"_", time, "_Zellconverter.dir")
dir.create(directory, showWarnings = FALSE)
```

Read in the Single Cell Experiment objects

```{r}
sce <- readRDS('20231107_09-33_Doublet.dir/RDS_objects.dir/doublet_filtered/SingleCellExp/MSK0785-Ach-Enth_doublet_filtered_SingleCellExp.rds')
sce
```

```{r}

# adata <- SCE2AnnData(sce) needs a python env
out_path <- tempfile(pattern = ".h5ad")
writeH5AD(sce, file = out_path) # not working

```

```{r}
library(basilisk)

roundtrip <- basiliskRun(fun = function(sce) {
     # Convert SCE to AnnData:
     adata <- zellkonverter::SCE2AnnData(sce)

     # Maybe do some work in Python on 'adata':
     # BLAH BLAH BLAH

     # Convert back to an SCE:
     # AnnData2SCE(adata)
}, env = zellkonverterAnnDataEnv(), sce = sce)
```

Try manually

```{r}
sce
```

```{r}
# save the counts matrix
library(anndata)
write_h5ad(counts(sce), test_h5ad.h5ad) #nope
counts(sce)
logcounts(sce)
decontXcounts(sce)
assays(sce)$decontXcounts
```

```{r}
reticulate::install_miniconda()
anndata::install_anndata()
```


```{r}
# create an Anndata object
ad <- AnnData(
    X = counts(sce),
    obs = colData(sce), 
    var = rowData(sce),
    layers = list(
        logcounts = logcounts(sce),
        decontX = assays(sce)$decontXcounts,
        soupX = assays(sce)$soupX
    # add obsm etc
    )
)

ad
```

